apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 3
  template:
    spec:
      containers:
      - name: my-app-container
        image: nginx
---
spec.replicas: 1
spec.template.spec.containers[0].image: nginx:1.19.10
