apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: web-app-deployment 
spec: 
  replicas: 3 
  selector: 
    matchLabels: 
      app: web-app 
  template: 
    metadata: 
      labels: 
        app: web-app 
    spec: 
      containers: 
        - name: web-app-container 
          image: shubhamdev2001/chandigarh-ai:latest 
          ports: 
            - containerPort: 80 
