apiVersion: apps/v1
kind: Deployment
metadata:
  name: inshine-deployment
  labels: 
    app: inshine
spec:
  replicas: 2
  selector:
    matchLabels:
      app: inshine
  template:
    metadata: 
      labels:
        app: inshine
    spec: 
      containers:
      - name: frontend
        image: shubhamdev2001/inshine-frontend
        ports: 
        - containerPort: 3000 

